# Causal Inference

### Matching

Given that the groups are imbalanced (GT option schools are more likely to be high income, less SWD, more students), can we balance the groups to get the ATE of the GT option on ELA and MATH scores?


```{r message=FALSE, warning=FALSE, include=FALSE}
#install and load packages
library(tidyverse)
library(readr)
library(tidyverse)
library(kableExtra)

data<- readRDS("/cloud/project/data/total_data_wide.RDS")
head(data[1:3,c(1:6,8:9)]) %>%
  kable(caption = "Sample Data Frame",
        col.names = c(" ", "DBN", "School Name",
                      "ENI", "% Male", "% Black", "%SWD", "% Poverty"))

## rename data frame
data <- data %>%
  rename(TotalEnrollment = `Total Enrollment`,
         ENI = `Economic Need Index`,
         PercentBlack = `% Black`,
         PercentWhite = `% White`,
         PercentSWD = `% Students with Disabilities`,
         PercentPoverty = `% Poverty`,
         PercentAsian = `% Asian`,
         PercentHispanic = `% Hispanic`,
         PercentELL = `% English Language Learners`,
         Percent_Attendance = `% Attendance`,
         Percent_Chron_Absent = `% Chronically Absent`,
         PercentMale= `% Male`)
small <- data %>%
  select(DBN, `School Name`, class_option, `3 2019.y`, `4 2019.y`, `5 2019.y`,
         `3 2019.x`, `4 2019.x`, `5 2019.x`, borough, school_type, TotalEnrollment,
         ENI, PercentMale, PercentSWD, PercentPoverty, PercentBlack,
         PercentELL, PercentAsian, PercentHispanic, Percent_Attendance, Percent_Chron_Absent) %>%
  mutate(GT_option = case_when(class_option %in% c("GT", "SC and GT") ~ "gifted option",
                               class_option %in% c("no option", "SC") ~ "no gifted option"),
         SC_option = case_when(class_option %in% c("SC", "SC and GT") ~ "SC option",
                               class_option %in% c("no option", "GT") ~ "no SC option"),
         treatment = ifelse(GT_option == "gifted option", 1, 0))

small$`3 2019.ela` <-gsub(",","",small$`3 2019.y`,fixed = TRUE)
small$`3 2019.math` <-gsub(",","",small$`3 2019.x`,fixed = TRUE)

```

```{r message=FALSE, warning=FALSE}

library(MatchIt)
library(cobalt)
school_nearest <- matchit(formula = treatment ~ ENI + PercentBlack +
                            TotalEnrollment + PercentSWD, 
                           data = small,
                          method = "nearest",
                           family = "binomial",
                          caliper = 0.25,
                          ratio = 6)

## balance improvement
bal.tab(school_nearest, m.threshold = 0.1)
bal.plot(school_nearest, var.name = 'TotalEnrollment', which = "both")
bal.plot(school_nearest, var.name = 'PercentBlack', which = "both")
bal.plot(school_nearest, var.name = 'PercentSWD', which = "both")
bal.plot(school_nearest, var.name = 'ENI', which = "both")


```
$$
\begin{align}
ELA_scores = \beta_0 +\beta_1GTOption + \epsilon
\end{align}
$$

```{r message=FALSE, warning=FALSE}
# 
 nearest_matched <- match.data(school_nearest)
# 
model_n <- lm(`3 2019.math` ~ treatment, data = nearest_matched)
summary(model_n)


```


### Heterogeneous Treatment Effects


### Within Borough Matching


### Outcome Models
